### ISSUE TITLE
Permalink leads to a 404

### ISSUE THREAD

**Issue by lonkelle** [starfishmod/WPAPI-SwaggerGenerator#3]
_example.com/index.php/apigenerate/swagger_ 
translates to 
_example.com/apigenerate/swagger_
and then 404s. 

Attempted to generate the file on a single site install, and multisite. Same issue on both.

**Comment by starfishmod** [comment]
Yep sorry it should be /index.php/**wp-json**/apigenerate/swagger

**Comment by starfishmod** [comment]
@JoelStickney I haven't tested multisite - please let me know how that goes if you can?

**Comment by lonkelle** [comment]
Perfect. :)

It also works (mostly) with multisite, unless it's a subdirectory install. Then the subdirectory of the sub-site should be placed in the 'basePath' rather than the 'host' section of the swagger file (like it is now). Adjusting that manually works perfectly - but it's something to consider for automating.
