### ISSUE TITLE
swagger.json does not pass JSON Schema Validator

### ISSUE THREAD

**Issue by timrsfo** [starfishmod/WPAPI-SwaggerGenerator#5]
Loaded plugin, and ran the generator to output swagger.json
goto [JSON Schema Validator](http://www.jsonschemavalidator.net/) , select schema  Swagger API 2.0
cut/paste swagger.json from WP.

many failures:
- first  operation names of all caps GET, POST, ... should be changed to lower-case as per schema.
- too many problems to list

NOTE: same validation works fine against petstore swagger.json

Swagger schema:  [OpenAPI-Specification/schemas/v2.0/schema.json](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json)

Swagger-Editor and Swagger-Validator did not like it either. 

Can you push and example of the swagger.json you are generating to this repo?
Please include a list of plugins your are using and versions.

I have some time to help in testing with external tools, unfortunately I don't know php.

I also used Convert [JSON to YAML Online](http://jsontoyaml.com/) to create yaml from the swagger.json file. 

Setup: Ubuntu Host, Docker WP/MySQL, Docker SwaggerUI

**Comment by starfishmod** [comment]
I will have a look at this soon - I see you point about the paths should be lower case.
I am unaware of other problems and I will put my out put through the validator you have suggested to see what issues there are. 

As to you question regarding plugins I have been using the standard WP-APIv2, the meta api, Oauth1 API and my own.

**Comment by timrsfo** [comment]
sounds like you are not seeing the errors I saw. Can you create an example dir and add the swagger.json file that you created on your end. or just attach it to a comment if that is easier for now.

I can do a compare/diff between your working version and mine and see whats up.

**Comment by starfishmod** [comment]
Ok I have pushed changes to fix the output to work with the validator - thanks for pointing this out!
